sorted_us_foods = [
    "Apple",
    "Artichoke",
    "Avocado",
    "BBQ sauce",
    "Bacon",
    "Bagel",
    "Banana",
    "Beef",
    "Beer",
    "Blueberries",
    "Bread",
    "Broccoli",
    "Butter",
    "Cabbage",
    "Candy",
    "Cantaloupe",
    "Carrot",
    "Cheese",
    "Cherry",
    "Chicken wings",
    "Cocktail",
    "Coconut",
    "Coffee",
    "Cookie",
    "Corn chips",
    "Cream",
    "Cucumber",
    "Doughnut",
    "Dumpling",
    "Egg",
    "Egg tart",
    "Eggplant",
    "Fish",
    "French fries",
    "Fries",
    "Garlic",
    "Grape",
    "Grapefruit",
    "Green beans",
    "Green onion",
    "Guacamole",
    "Hamburger",
    "Hamimelon",
    "Honey",
    "Ice cream",
    "Kiwi fruit",
    "Lemon",
    "Lettuce",
    "Lime",
    "Lobster",
    "Mango",
    "Meat ball",
    "Milk",
    "Muffin",
    "Mushroom",
    "Noodles",
    "Nuts",
    "Okra",
    "Olive oil",
    "Olives",
    "Onion",
    "Orange",
    "Orange juice",
    "Pancake",
    "Papaya",
    "Pasta",
    "Pastry",
    "Peach",
    "Pear",
    "Pepper",
    "Pie",
    "Pineapple",
    "Pizza",
    "Plum",
    "Pomegranate",
    "Popcorn",
    "Potato",
    "Prawns",
    "Pretzel",
    "Pumpkin",
    "Radish",
    "Red cabbage",
    "Rice",
    "Salad",
    "Salt",
    "Sandwich",
    "Sausages",
    "Soft drink",
    "Spinach",
    "Spring rolls",
    "Steak",
    "Strawberries",
    "Sushi",
    "Tea",
    "Tomato",
    "Tomato sauce",
    "Waffle",
    "Watermelon",
    "Wine",
    "Zucchini",
]

us_foods_data = [
    {
        "food": "Apple",
        "calories": 95,
        "protein": 0,
        "fat": 0,
        "carbs": 25,
        "vitamins": "A, C",
        "fiber": 4,
        "sodium": 2,
    },
    {
        "food": "Artichoke",
        "calories": 60,
        "protein": 4,
        "fat": 0,
        "carbs": 13,
        "vitamins": "C, K",
        "fiber": 7,
        "sodium": 120,
    },
    {
        "food": "Avocado",
        "calories": 320,
        "protein": 4,
        "fat": 29,
        "carbs": 17,
        "vitamins": "K, C",
        "fiber": 14,
        "sodium": 14,
    },
    {
        "food": "BBQ sauce",
        "calories": 30,
        "protein": 0,
        "fat": 0,
        "carbs": 7,
        "vitamins": None,
        "fiber": 0,
        "sodium": 300,
    },
    {
        "food": "Bacon",
        "calories": 43,
        "protein": 3,
        "fat": 3,
        "carbs": 0,
        "vitamins": None,
        "fiber": 0,
        "sodium": 190,
    },
    {
        "food": "Bagel",
        "calories": 245,
        "protein": 10,
        "fat": 1,
        "carbs": 48,
        "vitamins": "B",
        "fiber": 2,
        "sodium": 430,
    },
    {
        "food": "Banana",
        "calories": 105,
        "protein": 1,
        "fat": 0,
        "carbs": 27,
        "vitamins": "B6, C",
        "fiber": 3,
        "sodium": 1,
    },
    {
        "food": "Beef",
        "calories": 250,
        "protein": 26,
        "fat": 17,
        "carbs": 0,
        "vitamins": "B12",
        "fiber": 0,
        "sodium": 70,
    },
    {
        "food": "Beer",
        "calories": 154,
        "protein": 2,
        "fat": 0,
        "carbs": 13,
        "vitamins": None,
        "fiber": 0,
        "sodium": 14,
    },
    {
        "food": "Blueberries",
        "calories": 85,
        "protein": 1,
        "fat": 0,
        "carbs": 21,
        "vitamins": "C, K",
        "fiber": 4,
        "sodium": 1,
    },
    {
        "food": "Bread",
        "calories": 79,
        "protein": 3,
        "fat": 1,
        "carbs": 15,
        "vitamins": "B",
        "fiber": 1,
        "sodium": 140,
    },
    {
        "food": "Broccoli",
        "calories": 31,
        "protein": 3,
        "fat": 0,
        "carbs": 6,
        "vitamins": "C, K",
        "fiber": 2,
        "sodium": 30,
    },
    {
        "food": "Butter",
        "calories": 102,
        "protein": 0,
        "fat": 12,
        "carbs": 0,
        "vitamins": "A",
        "fiber": 0,
        "sodium": 91,
    },
    {
        "food": "Cabbage",
        "calories": 22,
        "protein": 1,
        "fat": 0,
        "carbs": 5,
        "vitamins": "C, K",
        "fiber": 2,
        "sodium": 16,
    },
    {
        "food": "Candy",
        "calories": 70,
        "protein": 0,
        "fat": 0,
        "carbs": 18,
        "vitamins": None,
        "fiber": 0,
        "sodium": 10,
    },
    {
        "food": "Cantaloupe",
        "calories": 54,
        "protein": 1,
        "fat": 0,
        "carbs": 13,
        "vitamins": "A, C",
        "fiber": 1,
        "sodium": 25,
    },
    {
        "food": "Carrot",
        "calories": 41,
        "protein": 1,
        "fat": 0,
        "carbs": 10,
        "vitamins": "A, K",
        "fiber": 3,
        "sodium": 69,
    },
    {
        "food": "Cheese",
        "calories": 113,
        "protein": 7,
        "fat": 9,
        "carbs": 1,
        "vitamins": "A, B12",
        "fiber": 0,
        "sodium": 174,
    },
    {
        "food": "Cherry",
        "calories": 50,
        "protein": 1,
        "fat": 0,
        "carbs": 12,
        "vitamins": "A, C",
        "fiber": 2,
        "sodium": 3,
    },
    {
        "food": "Chicken wings",
        "calories": 290,
        "protein": 31,
        "fat": 19,
        "carbs": 0,
        "vitamins": "B6",
        "fiber": 0,
        "sodium": 87,
    },
    {
        "food": "Cocktail",
        "calories": 150,
        "protein": 0,
        "fat": 0,
        "carbs": 15,
        "vitamins": None,
        "fiber": 0,
        "sodium": 10,
    },
    {
        "food": "Coconut",
        "calories": 354,
        "protein": 3,
        "fat": 33,
        "carbs": 15,
        "vitamins": "C, B",
        "fiber": 9,
        "sodium": 20,
    },
    {
        "food": "Coffee",
        "calories": 2,
        "protein": 0,
        "fat": 0,
        "carbs": 0,
        "vitamins": None,
        "fiber": 0,
        "sodium": 5,
    },
    {
        "food": "Cookie",
        "calories": 148,
        "protein": 2,
        "fat": 7,
        "carbs": 19,
        "vitamins": None,
        "fiber": 1,
        "sodium": 90,
    },
    {
        "food": "Corn chips",
        "calories": 152,
        "protein": 2,
        "fat": 8,
        "carbs": 18,
        "vitamins": None,
        "fiber": 1,
        "sodium": 170,
    },
    {
        "food": "Cream",
        "calories": 51,
        "protein": 0,
        "fat": 5,
        "carbs": 1,
        "vitamins": "A",
        "fiber": 0,
        "sodium": 16,
    },
    {
        "food": "Cucumber",
        "calories": 8,
        "protein": 0,
        "fat": 0,
        "carbs": 2,
        "vitamins": "K",
        "fiber": 0,
        "sodium": 1,
    },
    {
        "food": "Doughnut",
        "calories": 195,
        "protein": 2,
        "fat": 11,
        "carbs": 22,
        "vitamins": None,
        "fiber": 1,
        "sodium": 210,
    },
    {
        "food": "Dumpling",
        "calories": 40,
        "protein": 2,
        "fat": 1,
        "carbs": 5,
        "vitamins": None,
        "fiber": 0,
        "sodium": 50,
    },
    {
        "food": "Egg",
        "calories": 78,
        "protein": 6,
        "fat": 5,
        "carbs": 1,
        "vitamins": "A, D, B12",
        "fiber": 0,
        "sodium": 62,
    },
    {
        "food": "Egg tart",
        "calories": 190,
        "protein": 3,
        "fat": 9,
        "carbs": 24,
        "vitamins": "A",
        "fiber": 0,
        "sodium": 170,
    },
    {
        "food": "Eggplant",
        "calories": 25,
        "protein": 1,
        "fat": 0,
        "carbs": 6,
        "vitamins": "C",
        "fiber": 3,
        "sodium": 2,
    },
    {
        "food": "Fish",
        "calories": 206,
        "protein": 22,
        "fat": 12,
        "carbs": 0,
        "vitamins": "D, B12",
        "fiber": 0,
        "sodium": 60,
    },
    {
        "food": "French fries",
        "calories": 365,
        "protein": 4,
        "fat": 17,
        "carbs": 48,
        "vitamins": "C",
        "fiber": 3,
        "sodium": 270,
    },
    {
        "food": "Garlic",
        "calories": 4,
        "protein": 0,
        "fat": 0,
        "carbs": 1,
        "vitamins": "C",
        "fiber": 0,
        "sodium": 1,
    },
    {
        "food": "Grape",
        "calories": 69,
        "protein": 1,
        "fat": 0,
        "carbs": 18,
        "vitamins": "C, K",
        "fiber": 1,
        "sodium": 2,
    },
    {
        "food": "Grapefruit",
        "calories": 52,
        "protein": 1,
        "fat": 0,
        "carbs": 13,
        "vitamins": "C, A",
        "fiber": 2,
        "sodium": 0,
    },
    {
        "food": "Green beans",
        "calories": 31,
        "protein": 2,
        "fat": 0,
        "carbs": 7,
        "vitamins": "C, A",
        "fiber": 3,
        "sodium": 6,
    },
    {
        "food": "Green onion",
        "calories": 32,
        "protein": 2,
        "fat": 0,
        "carbs": 7,
        "vitamins": "K, C",
        "fiber": 2,
        "sodium": 16,
    },
    {
        "food": "Guacamole",
        "calories": 45,
        "protein": 1,
        "fat": 4,
        "carbs": 3,
        "vitamins": "K, C",
        "fiber": 3,
        "sodium": 130,
    },
    {
        "food": "Hamburger",
        "calories": 250,
        "protein": 12,
        "fat": 9,
        "carbs": 31,
        "vitamins": "B",
        "fiber": 1,
        "sodium": 378,
    },
    {
        "food": "Honey",
        "calories": 64,
        "protein": 0,
        "fat": 0,
        "carbs": 17,
        "vitamins": None,
        "fiber": 0,
        "sodium": 1,
    },
    {
        "food": "Ice cream",
        "calories": 137,
        "protein": 2,
        "fat": 7,
        "carbs": 16,
        "vitamins": "A",
        "fiber": 0,
        "sodium": 53,
    },
    {
        "food": "Kiwi fruit",
        "calories": 42,
        "protein": 1,
        "fat": 0,
        "carbs": 10,
        "vitamins": "C, K",
        "fiber": 2,
        "sodium": 2,
    },
    {
        "food": "Lemon",
        "calories": 17,
        "protein": 1,
        "fat": 0,
        "carbs": 5,
        "vitamins": "C",
        "fiber": 2,
        "sodium": 1,
    },
    {
        "food": "Lettuce",
        "calories": 5,
        "protein": 0,
        "fat": 0,
        "carbs": 1,
        "vitamins": "A, K",
        "fiber": 1,
        "sodium": 10,
    },
    {
        "food": "Lime",
        "calories": 20,
        "protein": 0,
        "fat": 0,
        "carbs": 7,
        "vitamins": "C",
        "fiber": 2,
        "sodium": 1,
    },
    {
        "food": "Lobster",
        "calories": 129,
        "protein": 27,
        "fat": 1,
        "carbs": 1,
        "vitamins": "B12",
        "fiber": 0,
        "sodium": 705,
    },
    {
        "food": "Mango",
        "calories": 60,
        "protein": 1,
        "fat": 0,
        "carbs": 15,
        "vitamins": "A, C",
        "fiber": 2,
        "sodium": 1,
    },
    {
        "food": "Meat ball",
        "calories": 200,
        "protein": 15,
        "fat": 15,
        "carbs": 3,
        "vitamins": "B",
        "fiber": 0,
        "sodium": 500,
    },
    {
        "food": "Milk",
        "calories": 103,
        "protein": 8,
        "fat": 2,
        "carbs": 12,
        "vitamins": "D, B12",
        "fiber": 0,
        "sodium": 107,
    },
    {
        "food": "Muffin",
        "calories": 340,
        "protein": 6,
        "fat": 16,
        "carbs": 44,
        "vitamins": "B",
        "fiber": 2,
        "sodium": 380,
    },
    {
        "food": "Mushroom",
        "calories": 22,
        "protein": 3,
        "fat": 0,
        "carbs": 3,
        "vitamins": "D, B",
        "fiber": 1,
        "sodium": 5,
    },
    {
        "food": "Noodles",
        "calories": 220,
        "protein": 8,
        "fat": 1,
        "carbs": 43,
        "vitamins": "B",
        "fiber": 2,
        "sodium": 1060,
    },
    {
        "food": "Nuts",
        "calories": 607,
        "protein": 20,
        "fat": 54,
        "carbs": 20,
        "vitamins": "E",
        "fiber": 9,
        "sodium": 1,
    },
    {
        "food": "Okra",
        "calories": 33,
        "protein": 2,
        "fat": 0,
        "carbs": 7,
        "vitamins": "C, K",
        "fiber": 3,
        "sodium": 7,
    },
    {
        "food": "Olive oil",
        "calories": 119,
        "protein": 0,
        "fat": 14,
        "carbs": 0,
        "vitamins": "E, K",
        "fiber": 0,
        "sodium": 0,
    },
    {
        "food": "Olives",
        "calories": 115,
        "protein": 1,
        "fat": 11,
        "carbs": 6,
        "vitamins": "E",
        "fiber": 3,
        "sodium": 735,
    },
    {
        "food": "Onion",
        "calories": 40,
        "protein": 1,
        "fat": 0,
        "carbs": 9,
        "vitamins": "C",
        "fiber": 2,
        "sodium": 4,
    },
    {
        "food": "Orange",
        "calories": 62,
        "protein": 1,
        "fat": 0,
        "carbs": 15,
        "vitamins": "C",
        "fiber": 3,
        "sodium": 0,
    },
    {
        "food": "Orange juice",
        "calories": 112,
        "protein": 2,
        "fat": 0,
        "carbs": 26,
        "vitamins": "C",
        "fiber": 0,
        "sodium": 2,
    },
    {
        "food": "Pancake",
        "calories": 227,
        "protein": 6,
        "fat": 8,
        "carbs": 32,
        "vitamins": "B",
        "fiber": 1,
        "sodium": 540,
    },
    {
        "food": "Papaya",
        "calories": 43,
        "protein": 1,
        "fat": 0,
        "carbs": 11,
        "vitamins": "A, C",
        "fiber": 2,
        "sodium": 8,
    },
    {
        "food": "Pasta",
        "calories": 200,
        "protein": 7,
        "fat": 1,
        "carbs": 40,
        "vitamins": "B",
        "fiber": 2,
        "sodium": 1,
    },
    {
        "food": "Pastry",
        "calories": 250,
        "protein": 4,
        "fat": 12,
        "carbs": 33,
        "vitamins": None,
        "fiber": 1,
        "sodium": 170,
    },
    {
        "food": "Peach",
        "calories": 59,
        "protein": 1,
        "fat": 0,
        "carbs": 14,
        "vitamins": "A, C",
        "fiber": 2,
        "sodium": 0,
    },
    {
        "food": "Pear",
        "calories": 101,
        "protein": 1,
        "fat": 0,
        "carbs": 27,
        "vitamins": "C, K",
        "fiber": 6,
        "sodium": 1,
    },
    {
        "food": "Pepper",
        "calories": 40,
        "protein": 2,
        "fat": 0,
        "carbs": 9,
        "vitamins": "A, C",
        "fiber": 3,
        "sodium": 4,
    },
    {
        "food": "Pie",
        "calories": 300,
        "protein": 3,
        "fat": 14,
        "carbs": 41,
        "vitamins": "A",
        "fiber": 1,
        "sodium": 300,
    },
    {
        "food": "Pineapple",
        "calories": 50,
        "protein": 1,
        "fat": 0,
        "carbs": 13,
        "vitamins": "C",
        "fiber": 1,
        "sodium": 1,
    },
    {
        "food": "Pizza",
        "calories": 285,
        "protein": 12,
        "fat": 10,
        "carbs": 36,
        "vitamins": "A, C",
        "fiber": 2,
        "sodium": 640,
    },
    {
        "food": "Plum",
        "calories": 30,
        "protein": 1,
        "fat": 0,
        "carbs": 8,
        "vitamins": "A, C",
        "fiber": 1,
        "sodium": 0,
    },
    {
        "food": "Pomegranate",
        "calories": 83,
        "protein": 2,
        "fat": 1,
        "carbs": 19,
        "vitamins": "C, K",
        "fiber": 4,
        "sodium": 3,
    },
    {
        "food": "Popcorn",
        "calories": 375,
        "protein": 11,
        "fat": 19,
        "carbs": 45,
        "vitamins": None,
        "fiber": 13,
        "sodium": 290,
    },
    {
        "food": "Potato",
        "calories": 161,
        "protein": 4,
        "fat": 0,
        "carbs": 37,
        "vitamins": "C, B6",
        "fiber": 4,
        "sodium": 17,
    },
    {
        "food": "Prawns",
        "calories": 99,
        "protein": 24,
        "fat": 0,
        "carbs": 0,
        "vitamins": "B12",
        "fiber": 0,
        "sodium": 111,
    },
    {
        "food": "Pretzel",
        "calories": 108,
        "protein": 3,
        "fat": 1,
        "carbs": 23,
        "vitamins": None,
        "fiber": 1,
        "sodium": 352,
    },
    {
        "food": "Pumpkin",
        "calories": 26,
        "protein": 1,
        "fat": 0,
        "carbs": 6,
        "vitamins": "A, C",
        "fiber": 1,
        "sodium": 1,
    },
    {
        "food": "Radish",
        "calories": 16,
        "protein": 1,
        "fat": 0,
        "carbs": 3,
        "vitamins": "C",
        "fiber": 2,
        "sodium": 39,
    },
    {
        "food": "Red cabbage",
        "calories": 31,
        "protein": 2,
        "fat": 0,
        "carbs": 7,
        "vitamins": "C, K",
        "fiber": 3,
        "sodium": 27,
    },
    {
        "food": "Rice",
        "calories": 206,
        "protein": 4,
        "fat": 0,
        "carbs": 45,
        "vitamins": "B",
        "fiber": 1,
        "sodium": 2,
    },
    {
        "food": "Salad",
        "calories": 20,
        "protein": 1,
        "fat": 0,
        "carbs": 4,
        "vitamins": "A, C, K",
        "fiber": 2,
        "sodium": 33,
    },
    {
        "food": "Salt",
        "calories": 0,
        "protein": 0,
        "fat": 0,
        "carbs": 0,
        "vitamins": None,
        "fiber": 0,
        "sodium": 2325,
    },
    {
        "food": "Sandwich",
        "calories": 290,
        "protein": 15,
        "fat": 10,
        "carbs": 35,
        "vitamins": "B",
        "fiber": 2,
        "sodium": 600,
    },
    {
        "food": "Sausages",
        "calories": 301,
        "protein": 12,
        "fat": 27,
        "carbs": 2,
        "vitamins": "B12",
        "fiber": 0,
        "sodium": 800,
    },
    {
        "food": "Soft drink",
        "calories": 140,
        "protein": 0,
        "fat": 0,
        "carbs": 39,
        "vitamins": None,
        "fiber": 0,
        "sodium": 30,
    },
    {
        "food": "Spinach",
        "calories": 23,
        "protein": 3,
        "fat": 0,
        "carbs": 4,
        "vitamins": "A, C, K",
        "fiber": 2,
        "sodium": 79,
    },
    {
        "food": "Spring rolls",
        "calories": 154,
        "protein": 4,
        "fat": 7,
        "carbs": 19,
        "vitamins": "A",
        "fiber": 1,
        "sodium": 390,
    },
    {
        "food": "Steak",
        "calories": 271,
        "protein": 26,
        "fat": 19,
        "carbs": 0,
        "vitamins": "B12",
        "fiber": 0,
        "sodium": 55,
    },
    {
        "food": "Strawberries",
        "calories": 32,
        "protein": 1,
        "fat": 0,
        "carbs": 8,
        "vitamins": "C",
        "fiber": 2,
        "sodium": 1,
    },
    {
        "food": "Sushi",
        "calories": 350,
        "protein": 8,
        "fat": 19,
        "carbs": 41,
        "vitamins": "B12",
        "fiber": 4,
        "sodium": 430,
    },
    {
        "food": "Tea",
        "calories": 2,
        "protein": 0,
        "fat": 0,
        "carbs": 0,
        "vitamins": None,
        "fiber": 0,
        "sodium": 7,
    },
    {
        "food": "Tomato",
        "calories": 18,
        "protein": 1,
        "fat": 0,
        "carbs": 4,
        "vitamins": "A, C",
        "fiber": 1,
        "sodium": 5,
    },
    {
        "food": "Tomato sauce",
        "calories": 29,
        "protein": 1,
        "fat": 0,
        "carbs": 7,
        "vitamins": "A, C",
        "fiber": 2,
        "sodium": 400,
    },
    {
        "food": "Waffle",
        "calories": 291,
        "protein": 8,
        "fat": 15,
        "carbs": 34,
        "vitamins": "B",
        "fiber": 1,
        "sodium": 466,
    },
    {
        "food": "Watermelon",
        "calories": 30,
        "protein": 1,
        "fat": 0,
        "carbs": 8,
        "vitamins": "A, C",
        "fiber": 0,
        "sodium": 1,
    },
    {
        "food": "Wine",
        "calories": 123,
        "protein": 0,
        "fat": 0,
        "carbs": 4,
        "vitamins": None,
        "fiber": 0,
        "sodium": 6,
    },
    {
        "food": "Zucchini",
        "calories": 17,
        "protein": 1,
        "fat": 0,
        "carbs": 3,
        "vitamins": "A, C",
        "fiber": 1,
        "sodium": 8,
    },
]


def get_us_food_data(food: str):
    for f in us_foods_data:
        if f["food"] == food:
            return f
    return None


sorted_indian_foods = [
    "burger",
    "butter_naan",
    "chai",
    "chapati",
    "chole_bhature",
    "dal_makhani",
    "dhokla",
    "fried_rice",
    "idli",
    "jalebi",
    "kaathi_rolls",
    "kadai_paneer",
    "kulfi",
    "dosa",
    "momos",
    "paani_puri",
    "pakode",
    "pav_bhaji",
    "pizza",
    "samosa",
]

ind_food_data = [
    {
        "food": "Butter Naan",
        "calories": 260,
        "protein": 7,
        "fat": 11,
        "carbs": 33,
        "vitamins": "B",
        "fiber": 2,
        "sodium": 400,
    },
    {
        "food": "Chai",
        "calories": 100,
        "protein": 3,
        "fat": 3,
        "carbs": 15,
        "vitamins": None,
        "fiber": 0,
        "sodium": 10,
    },
    {
        "food": "Chapati",
        "calories": 120,
        "protein": 3,
        "fat": 1,
        "carbs": 23,
        "vitamins": "B",
        "fiber": 2,
        "sodium": 5,
    },
    {
        "food": "Chole Bhature",
        "calories": 450,
        "protein": 12,
        "fat": 22,
        "carbs": 55,
        "vitamins": "C, B",
        "fiber": 8,
        "sodium": 600,
    },
    {
        "food": "Dal Makhani",
        "calories": 230,
        "protein": 9,
        "fat": 12,
        "carbs": 25,
        "vitamins": "B, Iron",
        "fiber": 6,
        "sodium": 350,
    },
    {
        "food": "Dhokla",
        "calories": 160,
        "protein": 5,
        "fat": 5,
        "carbs": 25,
        "vitamins": "B",
        "fiber": 3,
        "sodium": 300,
    },
    {
        "food": "Fried Rice",
        "calories": 280,
        "protein": 6,
        "fat": 8,
        "carbs": 45,
        "vitamins": "B",
        "fiber": 2,
        "sodium": 500,
    },
    {
        "food": "Idli",
        "calories": 150,
        "protein": 4,
        "fat": 1,
        "carbs": 30,
        "vitamins": "B",
        "fiber": 2,
        "sodium": 200,
    },
    {
        "food": "Jalebi",
        "calories": 300,
        "protein": 3,
        "fat": 15,
        "carbs": 40,
        "vitamins": None,
        "fiber": 0,
        "sodium": 10,
    },
    {
        "food": "Kaathi Rolls",
        "calories": 350,
        "protein": 15,
        "fat": 18,
        "carbs": 35,
        "vitamins": "B, C",
        "fiber": 3,
        "sodium": 600,
    },
    {
        "food": "Kadai Paneer",
        "calories": 320,
        "protein": 14,
        "fat": 25,
        "carbs": 10,
        "vitamins": "A, C",
        "fiber": 3,
        "sodium": 450,
    },
    {
        "food": "Kulfi",
        "calories": 220,
        "protein": 4,
        "fat": 11,
        "carbs": 28,
        "vitamins": "A, D",
        "fiber": 0,
        "sodium": 70,
    },
    {
        "food": "Dosa",
        "calories": 180,
        "protein": 4,
        "fat": 5,
        "carbs": 30,
        "vitamins": "B",
        "fiber": 2,
        "sodium": 300,
    },
    {
        "food": "Momos",
        "calories": 250,
        "protein": 8,
        "fat": 8,
        "carbs": 35,
        "vitamins": "B",
        "fiber": 2,
        "sodium": 400,
    },
    {
        "food": "Paani Puri",
        "calories": 180,
        "protein": 3,
        "fat": 7,
        "carbs": 25,
        "vitamins": "C",
        "fiber": 1,
        "sodium": 350,
    },
    {
        "food": "Pakode",
        "calories": 200,
        "protein": 5,
        "fat": 12,
        "carbs": 20,
        "vitamins": "A",
        "fiber": 2,
        "sodium": 300,
    },
    {
        "food": "Pav Bhaji",
        "calories": 300,
        "protein": 8,
        "fat": 12,
        "carbs": 40,
        "vitamins": "A, C",
        "fiber": 5,
        "sodium": 550,
    },
    {
        "food": "Samosa",
        "calories": 260,
        "protein": 4,
        "fat": 14,
        "carbs": 30,
        "vitamins": "A, C",
        "fiber": 2,
        "sodium": 350,
    },
]


def get_ind_food_data(food: str):
    aug_food = food.replace("_", " ").title()
    for f in ind_food_data:
        if f["food"] == aug_food:
            return f
    return None
