# Generated by Django 5.1.1 on 2024-09-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caloriecraft", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pantry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
            ],
        ),
    ]
