# Generated by Django 5.1.1 on 2024-09-13 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caloriecraft", "0002_pantry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="foodhistory",
            options={"verbose_name_plural": "Food Histories"},
        ),
        migrations.AlterModelOptions(
            name="pantry",
            options={"verbose_name_plural": "Pantries"},
        ),
        migrations.AddField(
            model_name="pantry",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
